export default function ReportModal({ stats, onClose }) {
  const mitigationRatio = stats.total > 0 ? ((stats.blocked / stats.total) * 100).toFixed(1) : 0;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-md flex items-center justify-center p-4 z-50 animate-[fadeIn_0.2s_ease-in]">
      {/* The ID here tells our CSS to ONLY print this box */}
      <div id="printable-report" className="bg-slate-900 border border-slate-700 rounded-2xl max-w-lg w-full p-7 shadow-2xl space-y-6">
        
        <div className="flex justify-between items-center border-b border-slate-800 pb-4">
          <div>
            <h3 className="text-xl font-bold text-slate-100 tracking-tight">Executive Threat Assessment</h3>
            <p className="text-xs text-slate-400 mt-1">Generated by SybilGuard Defense AI</p>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-200 print:hidden p-2">✕</button>
        </div>
        
        <div className="space-y-4 text-sm text-slate-300">
          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800">
            <div className="text-slate-400 text-xs uppercase tracking-wider font-semibold mb-1">Merchant Risk Profile</div>
            <div className="text-emerald-400 font-bold">Protected / SLA Compliant</div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="p-4 bg-slate-950 rounded-xl border border-slate-800">
              <div className="text-slate-500 text-xs font-semibold uppercase">Prevented Fraud</div>
              <div className="text-2xl font-mono font-bold text-emerald-400 mt-2">₹ {stats.savings.toLocaleString()}</div>
            </div>
            <div className="p-4 bg-slate-950 rounded-xl border border-slate-800">
              <div className="text-slate-500 text-xs font-semibold uppercase">Mitigation Ratio</div>
              <div className="text-2xl font-mono font-bold text-cyan-400 mt-2">{mitigationRatio}%</div>
            </div>
          </div>

          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800">
            <div className="font-bold text-slate-200 mb-2">Autonomous Actions Taken:</div>
            <ul className="list-disc list-inside text-slate-400 space-y-1.5">
              <li>Maintained ASN quarantine dynamically.</li>
              <li>Enabled 3DS step-up challenge on edge scores.</li>
              <li>Baselined {stats.total} total transaction samples.</li>
            </ul>
          </div>
        </div>

        {/* Buttons are hidden during printing via the print:hidden tailwind class */}
        <div className="flex justify-end space-x-3 pt-4 border-t border-slate-800 print:hidden">
          <button 
            onClick={handlePrint}
            className="px-5 py-2.5 bg-slate-800 hover:bg-slate-700 text-slate-200 font-medium text-sm rounded-lg transition-colors flex items-center space-x-2"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path></svg>
            <span>Export PDF</span>
          </button>
          <button 
            onClick={onClose}
            className="px-5 py-2.5 bg-gradient-to-r from-violet-600 to-cyan-600 hover:from-violet-500 hover:to-cyan-500 text-white font-medium text-sm rounded-lg transition-all shadow-lg"
          >
            Acknowledge
          </button>
        </div>
      </div>
    </div>
  );
}